import { PERMISSIONS } from './permission.constants.js';

/**
 * Perfis de utilizador pré-configurados, criados automaticamente para
 * toda nova organização (ver AuthService.register e seed/users.ts).
 * "Administrador" (acesso total) já é criado à parte com todas as permissões.
 */
export const ROLE_TEMPLATES: Array<{ name: string; description: string; permissionCodes: string[] }> = [
	{
		name: 'Diretor Geral',
		description: 'Visão e supervisão global da organização, sem gestão de permissões/papéis.',
		permissionCodes: [
			PERMISSIONS.USER_VIEW, PERMISSIONS.ROLE_VIEW, PERMISSIONS.ORGANIZATION_VIEW,
			PERMISSIONS.PLAN_VIEW, PERMISSIONS.MODULE_VIEW, PERMISSIONS.SETTING_VIEW,
			PERMISSIONS.STOCK_PRODUCT_VIEW, PERMISSIONS.STOCK_MOVEMENT_VIEW, PERMISSIONS.STOCK_REPORT_VIEW,
			PERMISSIONS.STOCK_CATEGORY_VIEW, PERMISSIONS.STOCK_SUPPLIER_VIEW, PERMISSIONS.STOCK_ENTRY_VIEW, PERMISSIONS.STOCK_EXIT_VIEW,
			PERMISSIONS.INVOICE_VIEW, PERMISSIONS.BILLING_RECEIPT_VIEW, PERMISSIONS.BILLING_PROFORMA_VIEW,
			PERMISSIONS.BILLING_CREDIT_NOTE_VIEW, PERMISSIONS.BILLING_QUOTE_VIEW, PERMISSIONS.BILLING_REPORT_VIEW,
			PERMISSIONS.CUSTOMER_VIEW,
			PERMISSIONS.TREASURY_ACCOUNT_VIEW, PERMISSIONS.TREASURY_CATEGORY_VIEW,
			PERMISSIONS.TREASURY_TRANSACTION_VIEW, PERMISSIONS.TREASURY_REPORT_VIEW,
		],
	},
	{
		name: 'Diretor Financeiro',
		description: 'Gestão financeira: tesouraria, faturação e relatórios financeiros.',
		permissionCodes: [
			PERMISSIONS.TREASURY_ACCOUNT_CREATE, PERMISSIONS.TREASURY_ACCOUNT_VIEW, PERMISSIONS.TREASURY_ACCOUNT_UPDATE,
			PERMISSIONS.TREASURY_CATEGORY_CREATE, PERMISSIONS.TREASURY_CATEGORY_VIEW, PERMISSIONS.TREASURY_CATEGORY_UPDATE,
			PERMISSIONS.TREASURY_TRANSACTION_CREATE, PERMISSIONS.TREASURY_TRANSACTION_VIEW, PERMISSIONS.TREASURY_TRANSACTION_UPDATE,
			PERMISSIONS.TREASURY_TRANSFER_CREATE, PERMISSIONS.TREASURY_REPORT_VIEW,
			PERMISSIONS.INVOICE_VIEW, PERMISSIONS.BILLING_REPORT_VIEW, PERMISSIONS.BILLING_TAX_MANAGE, PERMISSIONS.BILLING_SERIES_MANAGE,
			PERMISSIONS.BILLING_RECEIPT_VIEW, PERMISSIONS.CUSTOMER_VIEW,
			PERMISSIONS.SETTING_VIEW,
		],
	},
	{
		name: 'Gestor',
		description: 'Gestão operacional do dia a dia: stock, clientes e faturação básica.',
		permissionCodes: [
			PERMISSIONS.STOCK_PRODUCT_CREATE, PERMISSIONS.STOCK_PRODUCT_VIEW, PERMISSIONS.STOCK_PRODUCT_UPDATE,
			PERMISSIONS.STOCK_MOVEMENT_CREATE, PERMISSIONS.STOCK_MOVEMENT_VIEW,
			PERMISSIONS.STOCK_ENTRY_CREATE, PERMISSIONS.STOCK_ENTRY_VIEW, PERMISSIONS.STOCK_EXIT_CREATE, PERMISSIONS.STOCK_EXIT_VIEW,
			PERMISSIONS.STOCK_REPORT_VIEW, PERMISSIONS.STOCK_CATEGORY_VIEW, PERMISSIONS.STOCK_SUPPLIER_VIEW,
			PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_VIEW,
			PERMISSIONS.CUSTOMER_CREATE, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.CUSTOMER_UPDATE,
			PERMISSIONS.USER_VIEW,
		],
	},
	{
		name: 'Tesoureiro',
		description: 'Gestão de caixas, contas bancárias e movimentos de tesouraria.',
		permissionCodes: [
			PERMISSIONS.TREASURY_ACCOUNT_CREATE, PERMISSIONS.TREASURY_ACCOUNT_VIEW, PERMISSIONS.TREASURY_ACCOUNT_UPDATE,
			PERMISSIONS.TREASURY_CATEGORY_VIEW,
			PERMISSIONS.TREASURY_TRANSACTION_CREATE, PERMISSIONS.TREASURY_TRANSACTION_VIEW, PERMISSIONS.TREASURY_TRANSACTION_UPDATE,
			PERMISSIONS.TREASURY_TRANSFER_CREATE, PERMISSIONS.TREASURY_REPORT_VIEW,
			PERMISSIONS.BILLING_RECEIPT_VIEW, PERMISSIONS.CUSTOMER_VIEW,
		],
	},
	{
		name: 'Facturista',
		description: 'Emissão de faturas, proformas, recibos e gestão de clientes.',
		permissionCodes: [
			PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_VIEW, PERMISSIONS.INVOICE_UPDATE,
			PERMISSIONS.INVOICE_ISSUE, PERMISSIONS.INVOICE_SEND,
			PERMISSIONS.BILLING_PROFORMA_CREATE, PERMISSIONS.BILLING_PROFORMA_VIEW,
			PERMISSIONS.BILLING_QUOTE_CREATE, PERMISSIONS.BILLING_QUOTE_VIEW,
			PERMISSIONS.BILLING_RECEIPT_CREATE, PERMISSIONS.BILLING_RECEIPT_VIEW,
			PERMISSIONS.BILLING_POS_MANAGE,
			PERMISSIONS.CUSTOMER_CREATE, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.CUSTOMER_UPDATE,
		],
	},
	{
		name: 'Contabilista',
		description: 'Plano de contas, lançamentos contabilísticos, controlo fiscal e consulta de faturação/tesouraria.',
		permissionCodes: [
			PERMISSIONS.ACCOUNTING_ACCOUNT_VIEW, PERMISSIONS.ACCOUNTING_ACCOUNT_CREATE, PERMISSIONS.ACCOUNTING_ACCOUNT_UPDATE,
			PERMISSIONS.ACCOUNTING_ENTRY_VIEW, PERMISSIONS.ACCOUNTING_ENTRY_CREATE, PERMISSIONS.ACCOUNTING_REPORT_VIEW,
			PERMISSIONS.INVOICE_VIEW, PERMISSIONS.BILLING_REPORT_VIEW, PERMISSIONS.BILLING_TAX_MANAGE,
			PERMISSIONS.BILLING_RECEIPT_VIEW, PERMISSIONS.BILLING_CREDIT_NOTE_VIEW,
			PERMISSIONS.TREASURY_TRANSACTION_VIEW, PERMISSIONS.TREASURY_REPORT_VIEW, PERMISSIONS.TREASURY_ACCOUNT_VIEW,
			PERMISSIONS.STOCK_REPORT_VIEW, PERMISSIONS.CUSTOMER_VIEW,
		],
	},
	{
		name: 'Auditor',
		description: 'Acesso de apenas leitura a toda a operação, para fins de auditoria.',
		permissionCodes: [
			PERMISSIONS.USER_VIEW, PERMISSIONS.ROLE_VIEW, PERMISSIONS.PERMISSION_VIEW, PERMISSIONS.ORGANIZATION_VIEW,
			PERMISSIONS.PLAN_VIEW, PERMISSIONS.MODULE_VIEW, PERMISSIONS.SETTING_VIEW, PERMISSIONS.LOG_VIEW,
			PERMISSIONS.STOCK_PRODUCT_VIEW, PERMISSIONS.STOCK_MOVEMENT_VIEW, PERMISSIONS.STOCK_REPORT_VIEW,
			PERMISSIONS.STOCK_CATEGORY_VIEW, PERMISSIONS.STOCK_SUPPLIER_VIEW, PERMISSIONS.STOCK_ENTRY_VIEW, PERMISSIONS.STOCK_EXIT_VIEW,
			PERMISSIONS.INVOICE_VIEW, PERMISSIONS.BILLING_RECEIPT_VIEW, PERMISSIONS.BILLING_PROFORMA_VIEW,
			PERMISSIONS.BILLING_CREDIT_NOTE_VIEW, PERMISSIONS.BILLING_QUOTE_VIEW, PERMISSIONS.BILLING_REPORT_VIEW,
			PERMISSIONS.CUSTOMER_VIEW,
			PERMISSIONS.TREASURY_ACCOUNT_VIEW, PERMISSIONS.TREASURY_CATEGORY_VIEW,
			PERMISSIONS.TREASURY_TRANSACTION_VIEW, PERMISSIONS.TREASURY_REPORT_VIEW,
		],
	},
	{
		name: 'Operador',
		description: 'Operações básicas do dia a dia: movimentos de stock e vendas no POS.',
		permissionCodes: [
			PERMISSIONS.STOCK_MOVEMENT_CREATE, PERMISSIONS.STOCK_MOVEMENT_VIEW,
			PERMISSIONS.STOCK_ENTRY_CREATE, PERMISSIONS.STOCK_ENTRY_VIEW,
			PERMISSIONS.STOCK_EXIT_CREATE, PERMISSIONS.STOCK_EXIT_VIEW,
			PERMISSIONS.STOCK_PRODUCT_VIEW,
			PERMISSIONS.BILLING_POS_MANAGE, PERMISSIONS.BILLING_RECEIPT_CREATE,
			PERMISSIONS.CUSTOMER_VIEW,
		],
	},
];
